[project]
name = "uv-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.29.0",
]


[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
default = true
